const config = require('../config');
const { formatUptime } = require('../utils/helpers');

const categories = [
  { num: 1,  icon: '🌐', name: 'GENERAL',    count: 10  },
  { num: 2,  icon: '🤖', name: 'AI',          count: 18  },
  { num: 3,  icon: '📥', name: 'DOWNLOADER',  count: 8   },
  { num: 4,  icon: '🔧', name: 'TOOLS',       count: 82  },
  { num: 5,  icon: '🔍', name: 'SEARCH',      count: 15  },
  { num: 6,  icon: '👥', name: 'GROUP',       count: 104 },
  { num: 7,  icon: '👑', name: 'OWNER',       count: 108 },
  { num: 8,  icon: '⚙️', name: 'SETTINGS',   count: 27  },
  { num: 9,  icon: '🎉', name: 'FUN',         count: 36  },
  { num: 10, icon: '🔄', name: 'CONVERTER',   count: 5   },
  { num: 11, icon: '🕌', name: 'RELIGION',    count: 2   },
  { num: 12, icon: '📝', name: 'NOTES',       count: 7   },
  { num: 13, icon: '⚽', name: 'SPORTS',      count: 7   },
  { num: 14, icon: '⚡', name: 'GAME',        count: 18  },
  { num: 15, icon: '⚡', name: 'LOGO',        count: 29  },
  { num: 16, icon: '⚡', name: 'TEMPMAIL',    count: 5   },
  { num: 17, icon: '⚡', name: 'UPLOADER',    count: 5   },
  { num: 18, icon: '⚡', name: 'UTILITY',     count: 1   },
];

const commandLists = {
  1: [
    { cmd: '.botinfo',  desc: 'Show detailed bot information' },
    { cmd: '.chjid',    desc: 'Get WhatsApp Channel JID' },
    { cmd: '.help',     desc: 'Usage guide and quick help' },
    { cmd: '.list',     desc: 'Show all commands' },
    { cmd: '.menu',     desc: 'Browse commands by category' },
    { cmd: '.menus',    desc: 'Display bot uptime and info' },
    { cmd: '.met',      desc: 'Check group metadata' },
    { cmd: '.ping',     desc: 'Check bot response speed' },
    { cmd: '.repo',     desc: 'Fetch bot script' },
    { cmd: '.uptime',   desc: 'Check bot uptime' },
  ],
  2: [
    { cmd: '.ai',         desc: 'Chat with AI' },
    { cmd: '.aimodels',   desc: 'List all available AI models' },
    { cmd: '.chat',       desc: 'General AI chat assistant' },
    { cmd: '.claude',     desc: 'Chat with Claude AI' },
    { cmd: '.codex',      desc: 'AI coding assistant' },
    { cmd: '.gemini',     desc: 'Chat with Gemini AI' },
    { cmd: '.gpt',        desc: 'Chat with GPT-4o' },
    { cmd: '.gpt4',       desc: 'Chat with GPT-4' },
    { cmd: '.gpt4o',      desc: 'Chat with GPT-4o' },
    { cmd: '.gpt4o-mini', desc: 'Chat with GPT-4o-mini' },
    { cmd: '.guruai',     desc: 'Chat with GURU AI' },
    { cmd: '.imagine',    desc: 'Generate AI images' },
    { cmd: '.letmegpt',   desc: 'AI-powered web search' },
    { cmd: '.llama',      desc: 'Chat with Meta Llama' },
    { cmd: '.mistral',    desc: 'Chat with Mistral AI' },
    { cmd: '.openai',     desc: 'Chat with OpenAI GPT' },
    { cmd: '.searchai',   desc: 'AI-powered search' },
    { cmd: '.unity',      desc: 'Chat with Unity AI' },
  ],
  3: [
    { cmd: '.apk',       desc: 'Download Android APK' },
    { cmd: '.gdrive',    desc: 'Download from Google Drive' },
    { cmd: '.mediafire', desc: 'Download from MediaFire' },
    { cmd: '.pastebin',  desc: 'Fetch from Pastebin' },
    { cmd: '.play',      desc: 'Download audio from YouTube' },
    { cmd: '.spotify',   desc: 'Download Spotify tracks' },
    { cmd: '.tiktok',    desc: 'Download TikTok video' },
    { cmd: '.video',     desc: 'Download video from YouTube' },
  ],
  4: [
    { cmd: '.adfoc',      desc: 'Shorten URL with AdFoc.us' },
    { cmd: '.age',        desc: 'Calculate age from birthday' },
    { cmd: '.anagram',    desc: 'Check if two words are anagrams' },
    { cmd: '.ascii',      desc: 'Convert text to ASCII codes' },
    { cmd: '.base64',     desc: 'Encode/decode Base64' },
    { cmd: '.binary',     desc: 'Convert text to binary' },
    { cmd: '.bmi',        desc: 'Calculate BMI' },
    { cmd: '.caesar',     desc: 'Caesar cipher encode' },
    { cmd: '.calc',       desc: 'Calculate math expressions' },
    { cmd: '.camelcase',  desc: 'Convert text to camelCase' },
    { cmd: '.charcount',  desc: 'Count characters and words' },
    { cmd: '.color',      desc: 'Get info about a hex color' },
    { cmd: '.countdown',  desc: 'Count days until a date' },
    { cmd: '.createqr',   desc: 'Create a QR code' },
    { cmd: '.currency',   desc: 'Convert currency' },
    { cmd: '.define',     desc: 'Get word definition' },
    { cmd: '.domaincheck',desc: 'Check domain WHOIS info' },
    { cmd: '.factorial',  desc: 'Calculate factorial' },
    { cmd: '.fancy',      desc: 'Convert text to fancy fonts' },
    { cmd: '.fetch',      desc: 'Fetch content from URL' },
    { cmd: '.fibonacci',  desc: 'Get Fibonacci sequence' },
    { cmd: '.fromascii',  desc: 'Convert ASCII codes to text' },
    { cmd: '.isprime',    desc: 'Check if number is prime' },
    { cmd: '.longestword',desc: 'Find longest word in text' },
    { cmd: '.lower',      desc: 'Convert text to lowercase' },
    { cmd: '.morse',      desc: 'Convert text to Morse code' },
    { cmd: '.palindrome', desc: 'Check if text is palindrome' },
    { cmd: '.password',   desc: 'Generate secure password' },
    { cmd: '.percentof',  desc: 'Calculate percentage' },
    { cmd: '.pidigits',   desc: 'Get digits of Pi' },
    { cmd: '.readqr',     desc: 'Read/decode a QR code' },
    { cmd: '.remindme',   desc: 'Set a personal reminder' },
    { cmd: '.repeattext', desc: 'Repeat text N times' },
    { cmd: '.reversetext',desc: 'Reverse a text string' },
    { cmd: '.roman',      desc: 'Convert to Roman numerals' },
    { cmd: '.rot13',      desc: 'ROT13 encode/decode' },
    { cmd: '.shuffletext',desc: 'Shuffle words in sentence' },
    { cmd: '.snakecase',  desc: 'Convert to snake_case' },
    { cmd: '.splittext',  desc: 'Split text by delimiter' },
    { cmd: '.temperature',desc: 'Convert temperature units' },
    { cmd: '.tinyurl',    desc: 'Shorten URL with TinyURL' },
    { cmd: '.tip',        desc: 'Calculate tip amount' },
    { cmd: '.titlecase',  desc: 'Convert to Title Case' },
    { cmd: '.translate',  desc: 'Translate text to any language' },
    { cmd: '.ttp',        desc: 'Convert text to picture' },
    { cmd: '.unmorse',    desc: 'Convert Morse code to text' },
    { cmd: '.unroman',    desc: 'Convert Roman numerals to number' },
    { cmd: '.upper',      desc: 'Convert text to UPPERCASE' },
    { cmd: '.uuid',       desc: 'Generate random UUID v4' },
    { cmd: '.vowelcount', desc: 'Count vowels and consonants' },
    { cmd: '.vvsave',     desc: 'Save view-once messages' },
    { cmd: '.weather',    desc: 'Get weather for a location' },
    { cmd: '.wordcount',  desc: 'Count words and characters' },
  ],
  5: [
    { cmd: '.apkmirror',    desc: 'Search APK Mirror' },
    { cmd: '.ggleimage',    desc: 'Search Google Images' },
    { cmd: '.google',       desc: 'Search Google' },
    { cmd: '.happymod',     desc: 'Search HappyMod' },
    { cmd: '.lyrics',       desc: 'Get song lyrics' },
    { cmd: '.npm',          desc: 'Search NPM packages' },
    { cmd: '.shazam',       desc: 'Identify music from audio' },
    { cmd: '.spotifysearch',desc: 'Search Spotify tracks' },
    { cmd: '.stickersearch',desc: 'Search stickers' },
    { cmd: '.unsplash',     desc: 'Search Unsplash photos' },
    { cmd: '.urban',        desc: 'Urban Dictionary lookup' },
    { cmd: '.wallpapers',   desc: 'Search HD wallpapers' },
    { cmd: '.wattpad',      desc: 'Search Wattpad stories' },
    { cmd: '.weather',      desc: 'Get weather information' },
    { cmd: '.yts',          desc: 'Search YouTube' },
  ],
  6: [
    { cmd: '.accept',         desc: 'Accept pending join request' },
    { cmd: '.acceptall',      desc: 'Accept all join requests' },
    { cmd: '.add',            desc: 'Add user to group' },
    { cmd: '.antidemote',     desc: 'Toggle anti-demote' },
    { cmd: '.antiflood',      desc: 'Toggle anti-flood' },
    { cmd: '.antiforeign',    desc: 'Toggle anti-foreign' },
    { cmd: '.antiforward',    desc: 'Toggle anti-forward' },
    { cmd: '.antipromote',    desc: 'Toggle anti-promote' },
    { cmd: '.antispam',       desc: 'Toggle anti-spam' },
    { cmd: '.antisticker',    desc: 'Toggle anti-sticker' },
    { cmd: '.antiviewonce',   desc: 'Toggle anti-viewonce' },
    { cmd: '.autokick',       desc: 'Permanently ban a user' },
    { cmd: '.autokicklist',   desc: 'List permanent bans' },
    { cmd: '.badwords',       desc: 'Manage bad words list' },
    { cmd: '.clearwarn',      desc: 'Clear member warnings' },
    { cmd: '.del',            desc: 'Delete a quoted message' },
    { cmd: '.demote',         desc: 'Demote admin to member' },
    { cmd: '.disapp',         desc: 'Toggle disappearing messages' },
    { cmd: '.everyone',       desc: 'Tag all members' },
    { cmd: '.gcdesc',         desc: 'Change group description' },
    { cmd: '.gcpp',           desc: 'Set group profile picture' },
    { cmd: '.getgcpp',        desc: 'Download group picture' },
    { cmd: '.getlid',         desc: 'Get User JID from LID' },
    { cmd: '.ghostkick',      desc: 'Kick inactive members' },
    { cmd: '.goodbyemessage', desc: 'Set goodbye message' },
    { cmd: '.groupname',      desc: 'Change group name' },
    { cmd: '.groupsettings',  desc: 'View group settings' },
    { cmd: '.groupstats',     desc: 'Show group statistics' },
    { cmd: '.hidetag',        desc: 'Tag members silently' },
    { cmd: '.kick',           desc: 'Remove user from group' },
    { cmd: '.killgc',         desc: 'Terminate group' },
    { cmd: '.left',           desc: 'Bot leaves the group' },
    { cmd: '.link',           desc: 'Get group invite link' },
    { cmd: '.listadmins',     desc: 'List all admins' },
    { cmd: '.listmembers',    desc: 'List all members' },
    { cmd: '.lockall',        desc: 'Lock all message types' },
    { cmd: '.lockdown',       desc: 'Emergency group freeze' },
    { cmd: '.massdm',         desc: 'DM every group member' },
    { cmd: '.mute',           desc: 'Close group chat' },
    { cmd: '.newgroup',       desc: 'Create a new group' },
    { cmd: '.nuke',           desc: 'Kick all non-admins' },
    { cmd: '.promote',        desc: 'Promote member to admin' },
    { cmd: '.reject',         desc: 'Reject join request' },
    { cmd: '.rejectall',      desc: 'Reject all join requests' },
    { cmd: '.resetgroup',     desc: 'Reset all group settings' },
    { cmd: '.resetlink',      desc: 'Reset group invite link' },
    { cmd: '.restrictions',   desc: 'View group restrictions' },
    { cmd: '.setantibad',     desc: 'Set anti-badwords' },
    { cmd: '.setantilink',    desc: 'Set anti-link' },
    { cmd: '.setgoodbye',     desc: 'Set goodbye message' },
    { cmd: '.setwelcome',     desc: 'Set welcome message' },
    { cmd: '.shadowban',      desc: 'Shadow ban a member' },
    { cmd: '.shadowlist',     desc: 'List shadow-banned members' },
    { cmd: '.shadowunban',    desc: 'Remove shadow ban' },
    { cmd: '.slowmode',       desc: 'Set slow mode delay' },
    { cmd: '.tagadmins',      desc: 'Tag all admins' },
    { cmd: '.tagall',         desc: 'Tag all members' },
    { cmd: '.unautokick',     desc: 'Remove permanent ban' },
    { cmd: '.unlockall',      desc: 'Unlock all message types' },
    { cmd: '.unlockdown',     desc: 'Lift lockdown' },
    { cmd: '.unmute',         desc: 'Open group chat' },
    { cmd: '.vcf',            desc: 'Export members as VCF' },
    { cmd: '.warn',           desc: 'Warn a group member' },
    { cmd: '.warnlist',       desc: 'List all warned members' },
    { cmd: '.warns',          desc: 'Check member warnings' },
    { cmd: '.welcomemessage', desc: 'Set welcome message' },
  ],
  7: [
    { cmd: '.>',              desc: 'Evaluate JavaScript code' },
    { cmd: '.$',              desc: 'Execute shell commands' },
    { cmd: '.addchannel',     desc: 'Add channel to auto-follow' },
    { cmd: '.addchat',        desc: 'Add chat to greetings list' },
    { cmd: '.adminclearnotes',desc: 'Delete all notes for user' },
    { cmd: '.admindelnote',   desc: 'Delete any note by ID' },
    { cmd: '.allnotes',       desc: 'View all users notes' },
    { cmd: '.announce',       desc: 'Send announcement' },
    { cmd: '.autorestart',    desc: 'Auto-restart bot every N hours' },
    { cmd: '.block',          desc: 'Block a user' },
    { cmd: '.blocklist',      desc: 'List all blocked contacts' },
    { cmd: '.botstats',       desc: 'Show bot statistics' },
    { cmd: '.broadcast',      desc: 'Broadcast to all groups' },
    { cmd: '.delsudo',        desc: 'Remove sudo user' },
    { cmd: '.forward',        desc: 'Forward quoted message' },
    { cmd: '.getinvite',      desc: 'Get invite link for any group' },
    { cmd: '.getpp',          desc: 'Download profile picture' },
    { cmd: '.getsetting',     desc: 'Get a setting value' },
    { cmd: '.getsudo',        desc: 'Get all sudo users' },
    { cmd: '.gmsg',           desc: 'Set Good Morning message' },
    { cmd: '.gnmsg',          desc: 'Set Good Night message' },
    { cmd: '.greetings',      desc: 'Toggle morning/night greetings' },
    { cmd: '.groupinfo',      desc: 'Get info about any group' },
    { cmd: '.jid',            desc: 'Get User/Group JID' },
    { cmd: '.join',           desc: 'Join group via invite link' },
    { cmd: '.mygroups',       desc: 'List all groups bot is in' },
    { cmd: '.owner',          desc: 'Get bot owner info' },
    { cmd: '.pair',           desc: 'Generate pairing code' },
    { cmd: '.pp',             desc: 'Set new profile picture' },
    { cmd: '.purge',          desc: 'Delete last N messages' },
    { cmd: '.removechannel',  desc: 'Remove channel from auto-follow' },
    { cmd: '.report',         desc: 'Request new features' },
    { cmd: '.resetallsettings',desc: 'Reset all settings' },
    { cmd: '.resetdb',        desc: 'Reset entire database' },
    { cmd: '.resetsudo',      desc: 'Remove all sudo numbers' },
    { cmd: '.resetwarns',     desc: 'Reset all warnings' },
    { cmd: '.save',           desc: 'Save messages' },
    { cmd: '.setanticall',    desc: 'Set anticall mode' },
    { cmd: '.setantidelete',  desc: 'Set antidelete mode' },
    { cmd: '.setautobio',     desc: 'Set auto bio' },
    { cmd: '.setautolikestatus',desc: 'Set auto like status' },
    { cmd: '.setautoreact',   desc: 'Set auto react mode' },
    { cmd: '.setautoread',    desc: 'Set auto read mode' },
    { cmd: '.setautoreadstatus',desc: 'Set auto read status' },
    { cmd: '.setautoreply',   desc: 'Set auto reply' },
    { cmd: '.setbotname',     desc: 'Set bot name' },
    { cmd: '.setexpiry',      desc: 'Set bot expiry date' },
    { cmd: '.setmode',        desc: 'Set bot mode' },
    { cmd: '.setownernumber', desc: 'Set owner number' },
    { cmd: '.setprefix',      desc: 'Set bot prefix' },
    { cmd: '.setsetting',     desc: 'Set any setting' },
    { cmd: '.setsudo',        desc: 'Set sudo user' },
    { cmd: '.settimezone',    desc: 'Set bot timezone' },
    { cmd: '.settings',       desc: 'View all bot settings' },
    { cmd: '.stalk',          desc: 'Track user online status' },
    { cmd: '.tostatus',       desc: 'Forward message to status' },
    { cmd: '.unblock',        desc: 'Unblock a user' },
    { cmd: '.unstalk',        desc: 'Stop tracking user' },
    { cmd: '.update',         desc: 'Check and apply updates' },
    { cmd: '.vv',             desc: 'Reveal view once media' },
    { cmd: '.whois',          desc: 'Get full user profile' },
  ],
  8: [
    { cmd: '.antiflood',       desc: 'Toggle anti-flood' },
    { cmd: '.autoplugs',       desc: 'View/toggle auto-plugins' },
    { cmd: '.disappearlog',    desc: 'Toggle disappearing msg log' },
    { cmd: '.dmpermit',        desc: 'Toggle DM permit mode' },
    { cmd: '.dmpermitaction',  desc: 'Set action for blocked DMs' },
    { cmd: '.dmpermitmsg',     desc: 'Set blocked DM message' },
    { cmd: '.dmstatus',        desc: 'View DM permit config' },
    { cmd: '.dmwhitelist',     desc: 'Manage DM whitelist' },
    { cmd: '.floodaction',     desc: 'Set flood action' },
    { cmd: '.keyworddm',       desc: 'Toggle keyword auto-DM' },
    { cmd: '.mentionalert',    desc: 'Toggle mention alert' },
    { cmd: '.polltracker',     desc: 'Toggle poll tracker' },
    { cmd: '.pttsave',         desc: 'Toggle PTT/audio save' },
    { cmd: '.setautomute',     desc: 'Auto-mute groups on restart' },
    { cmd: '.setbiotext',      desc: 'Set bot WhatsApp bio' },
    { cmd: '.setbotlang',      desc: 'Set bot language' },
    { cmd: '.setbotname',      desc: 'Set bot display name' },
    { cmd: '.setbotprefix',    desc: 'Change command prefix' },
    { cmd: '.setrejectcall',   desc: 'Auto-reject incoming calls' },
    { cmd: '.setspamfilter',   desc: 'Toggle global spam filter' },
    { cmd: '.settagprotect',   desc: 'Protect against mass-tag' },
    { cmd: '.settingsinfo',    desc: 'View all settings summary' },
    { cmd: '.setwarnlimit',    desc: 'Set warns before kick' },
    { cmd: '.setwelcomeaction',desc: 'Action when bot added' },
    { cmd: '.statussaver',     desc: 'Toggle status saver' },
    { cmd: '.vvreact',         desc: 'Toggle VV react save' },
    { cmd: '.vvtracker',       desc: 'Auto-save view once media' },
  ],
  9: [
    { cmd: '.8ball',      desc: 'Ask the magic 8-ball' },
    { cmd: '.acronym',    desc: 'Create an acronym from text' },
    { cmd: '.choose',     desc: 'Pick from options' },
    { cmd: '.coin',       desc: 'Flip a coin' },
    { cmd: '.compliment', desc: 'Send a compliment' },
    { cmd: '.confession', desc: 'Post anonymous confession' },
    { cmd: '.dare',       desc: 'Get a random dare' },
    { cmd: '.datefact',   desc: 'Get historical date fact' },
    { cmd: '.dice',       desc: 'Roll a dice' },
    { cmd: '.emojify',    desc: 'Add emojis to text' },
    { cmd: '.fact',       desc: 'Get a random fact' },
    { cmd: '.fakechat',   desc: 'Generate fake WhatsApp chat' },
    { cmd: '.fakeid',     desc: 'Generate fake identity' },
    { cmd: '.flip',       desc: 'Flip a coin' },
    { cmd: '.joke',       desc: 'Get a random joke' },
    { cmd: '.meme',       desc: 'Get a random meme' },
    { cmd: '.mock',       desc: 'SpongeBob mocking text' },
    { cmd: '.number',     desc: 'Get fun number facts' },
    { cmd: '.quote',      desc: 'Get inspirational quote' },
    { cmd: '.random',     desc: 'Generate random number' },
    { cmd: '.rate',       desc: 'Rate something out of 10' },
    { cmd: '.repeat',     desc: 'Repeat text N times' },
    { cmd: '.riddle',     desc: 'Get a random riddle' },
    { cmd: '.rizz',       desc: 'Generate a pickup line' },
    { cmd: '.roast',      desc: 'Roast someone' },
    { cmd: '.roll',       desc: 'Roll a dice' },
    { cmd: '.scorecard',  desc: 'Generate fun scorecard' },
    { cmd: '.ship',       desc: 'Check love compatibility' },
    { cmd: '.trivia',     desc: 'Get a trivia question' },
    { cmd: '.truth',      desc: 'Get a truth question' },
    { cmd: '.zodiac',     desc: 'Get zodiac sign info' },
  ],
  10: [
    { cmd: '.sticker', desc: 'Convert image to sticker' },
    { cmd: '.toaudio', desc: 'Convert video to audio' },
    { cmd: '.toimg',   desc: 'Convert sticker to image' },
    { cmd: '.toptt',   desc: 'Convert audio to PTT' },
    { cmd: '.tovideo', desc: 'Convert audio to video' },
  ],
  11: [
    { cmd: '.bible', desc: 'Get Bible verses' },
    { cmd: '.quran', desc: 'Get Quran verses' },
  ],
  12: [
    { cmd: '.note',      desc: 'Save a note' },
    { cmd: '.notes',     desc: 'List your notes' },
    { cmd: '.delnote',   desc: 'Delete a note by ID' },
    { cmd: '.clearnotes',desc: 'Delete all your notes' },
    { cmd: '.getnote',   desc: 'Get a note by ID' },
    { cmd: '.updatenote',desc: 'Update a note by ID' },
    { cmd: '.pinnote',   desc: 'Pin a note' },
  ],
  13: [
    { cmd: '.fixtures',  desc: 'Get upcoming fixtures' },
    { cmd: '.h2h',       desc: 'Head-to-head stats' },
    { cmd: '.livescore', desc: 'Get live sports scores' },
    { cmd: '.playerinfo',desc: 'Get player info' },
    { cmd: '.standings', desc: 'Get league standings' },
    { cmd: '.teaminfo',  desc: 'Get team info' },
    { cmd: '.topscorer', desc: 'Get top scorers' },
  ],
  14: [
    { cmd: '.akinator',  desc: 'Akinator guessing game' },
    { cmd: '.anagram',   desc: 'Anagram game' },
    { cmd: '.blackjack', desc: 'Play Blackjack' },
    { cmd: '.casino',    desc: 'Play casino games' },
    { cmd: '.chess',     desc: 'Play Chess' },
    { cmd: '.guess',     desc: 'Guess the number game' },
    { cmd: '.hangman',   desc: 'Play Hangman' },
    { cmd: '.math',      desc: 'Math challenge game' },
    { cmd: '.numguess',  desc: 'Number guessing game' },
    { cmd: '.quiz',      desc: 'Play a quiz game' },
    { cmd: '.riddle',    desc: 'Riddle game' },
    { cmd: '.rps',       desc: 'Rock Paper Scissors' },
    { cmd: '.scramble',  desc: 'Word scramble game' },
    { cmd: '.slots',     desc: 'Play slot machine' },
    { cmd: '.snake',     desc: 'Play Snake game' },
    { cmd: '.tictactoe', desc: 'Play Tic-Tac-Toe' },
    { cmd: '.wordchain', desc: 'Word chain game' },
    { cmd: '.wordle',    desc: 'Play Wordle' },
  ],
  15: [
    { cmd: '.3dlogo',       desc: 'Generate 3D logo' },
    { cmd: '.alien',        desc: 'Generate alien text' },
    { cmd: '.blood',        desc: 'Generate blood text' },
    { cmd: '.chrome',       desc: 'Generate chrome text' },
    { cmd: '.comic',        desc: 'Generate comic text' },
    { cmd: '.crystal',      desc: 'Generate crystal text' },
    { cmd: '.cyberpunklogo',desc: 'Generate cyberpunk logo' },
    { cmd: '.dark',         desc: 'Generate dark text' },
    { cmd: '.digital',      desc: 'Generate digital text' },
    { cmd: '.firelogo',     desc: 'Generate fire logo' },
    { cmd: '.flaming',      desc: 'Generate flaming text' },
    { cmd: '.galaxy',       desc: 'Generate galaxy text' },
    { cmd: '.glitchlogo',   desc: 'Generate glitch logo' },
    { cmd: '.goldenlogo',   desc: 'Generate golden logo' },
    { cmd: '.gradientlogo', desc: 'Generate gradient logo' },
    { cmd: '.graffiti',     desc: 'Generate graffiti text' },
    { cmd: '.icelogo',      desc: 'Generate ice logo' },
    { cmd: '.ink',          desc: 'Generate ink text' },
    { cmd: '.matrix',       desc: 'Generate matrix text' },
    { cmd: '.neonlogo',     desc: 'Generate neon logo' },
    { cmd: '.poison',       desc: 'Generate poison text' },
    { cmd: '.pop',          desc: 'Generate pop art text' },
    { cmd: '.rainbow',      desc: 'Generate rainbow text' },
    { cmd: '.retrologo',    desc: 'Generate retro logo' },
    { cmd: '.shadowlogo',   desc: 'Generate shadow logo' },
    { cmd: '.sketch',       desc: 'Generate sketch text' },
    { cmd: '.thunder',      desc: 'Generate thunder text' },
    { cmd: '.vintage',      desc: 'Generate vintage text' },
    { cmd: '.zombie',       desc: 'Generate zombie text' },
  ],
  16: [
    { cmd: '.checkinbox',  desc: 'Check temp email inbox' },
    { cmd: '.deletemail',  desc: 'Delete temp email' },
    { cmd: '.readmail',    desc: 'Read a specific email' },
    { cmd: '.refreshmail', desc: 'Refresh email inbox' },
    { cmd: '.tempmail',    desc: 'Generate temp email address' },
  ],
  17: [
    { cmd: '.catbox',  desc: 'Upload file to Catbox' },
    { cmd: '.fileio',  desc: 'Upload file to File.io' },
    { cmd: '.imgbb',   desc: 'Upload image to ImgBB' },
    { cmd: '.pomf',    desc: 'Upload file to Pomf' },
    { cmd: '.uguu',    desc: 'Upload file to Uguu' },
  ],
  18: [
    { cmd: '.pair', desc: 'Get pairing code & channel info' },
  ],
};

const TOTAL_COMMANDS = Object.values(commandLists).reduce((a, b) => a + b.length, 0);

function getMainMenu(username, totalCmds, uptime) {
  let menu = `╰► Hey, @${username}\n`;
  menu += `╭───〔  *ULTRA 𝖝𝖒𝖆𝖓𓅂*  〕──────┈⊷𑲭𑲭𑲭𑲭𑲭𑲭𑲭𑲭𑲭𑲭\n`;
  menu += `├──────────────────────\n`;
  menu += `│✵│▸ 📊 *TOTAL COMMANDS:* ${totalCmds}\n`;
  menu += `│✵│▸ ⏱️ *UPTIME:* ${uptime}\n`;
  menu += `│✵│▸ ⚡ *PREFIX:* ${config.PREFIX}\n`;
  menu += `│✵│▸ ⚙️ *MODE:* ${config.MODE}\n`;
  menu += `│✵│▸ 📦 *VERSION:* ${config.VERSION}\n`;
  menu += `│✵│▸ 🔑 *LICENSE:* ♾️  LIFETIME LICENSE\n`;
  menu += `│✵│▸ 📅 *EXPIRY:* No expiry set · Always active\n`;
  menu += `╰──────────────────────────────⊷\n\n`;
  menu += `╭───◇ *𝗖𝗔𝗧𝗘𝗚𝗢𝗥𝗜𝗘𝗦* ◇──────┈⊷\n`;
  menu += `│「 Tap the button below or reply with a number 」\n`;
  categories.forEach(c => {
    menu += `> │◦➛ ${c.num}. ${c.icon} ${c.name}  _(${c.count} cmds)_\n`;
  });
  menu += `╰─────────────────────┈⊷\n`;
  menu += `> ✨ _Powered by DECENT TECH😎_`;
  return menu;
}

function getCategoryMenu(num) {
  const cat = categories.find(c => c.num === num);
  if (!cat) return null;
  const cmds = commandLists[num] || [];
  let menu = `╭───〔 *${cat.icon} ${cat.name} COMMANDS* 〕──────┈⊷𑲭𑲭𑲭𑲭𑲭𑲭𑲭𑲭𑲭𑲭\n`;
  menu += `├──────────────────────\n`;
  menu += `│✵│▸ 📊 *TOTAL:* ${cmds.length} commands\n`;
  menu += `│✵│▸ ⚡ *PREFIX:* ${config.PREFIX}\n`;
  menu += `├──────────────────────\n│\n`;
  cmds.forEach(c => {
    menu += `> │◈ *${c.cmd.padEnd(20)}* › _${c.desc}_\n> │\n`;
  });
  menu += `╰─────────────────────┈⊷\n`;
  menu += `  💬 _Reply_ *0* _to go back to menu_\n`;
  menu += `> ✨ _Powered by DECENT 😎_`;
  return menu;
}

module.exports = { categories, commandLists, TOTAL_COMMANDS, getMainMenu, getCategoryMenu };
